export const inputsProperties = [
  {
    labelContent: "Username",
    rhfName: "username",
    id: "username",
    type: "text",
    autoComplete: "on",
    rhfRequiredMessage: "Username is required",
    rhfMinLengthMessage: "Username must be at least 3 characters long",
    rhfMinLengthValue: 3,
    rhfMaxLengthMessage: "Username cannot exceed 20 characters",
    rhfMaxLengthValue: 20,
    inputStyle: "user",
  },
  {
    labelContent: "Email",
    rhfName: "email",
    id: "email",
    type: "text",
    autoComplete: "on",
    rhfRequiredMessage: "Email is required",
    rhfPatternValue: /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/i,
    rhfPatternMessage: "Invalid email address",
    inputStyle: "user",
  },
  {
    labelContent: "Password",
    rhfName: "password",
    id: "password",
    type: "password",
    rhfRequiredMessage: "Password is required",
    rhfMinLengthMessage: "Password must be at least 6 characters long",
    rhfMinLengthValue: 6,
    rhfMaxLengthMessage: "Password cannot exceed 40 characters",
    rhfMaxLengthValue: 40,
    inputStyle: "user",
  },
  {
    labelContent: "Repeat Password",
    rhfName: "repeatPassword",
    id: "repeatPassword",
    type: "password",
    rhfRequiredMessage: "Repeat password is required",
    validateWith: "password",
    inputStyle: "user",
  },
  {
    labelContent: "I agree to the processing of my personal information",
    rhfName: "personalData",
    id: "personalData",
    type: "checkbox",
    rhfRequiredMessage: "Consent to personal data processing is required",
    inputStyle: "checkbox",
  },
];
